export const theme = {
    normal: {
        wrapper: "#EAEEF6",
        header: "#FFF",
        logo: "#FFF",
        userNameColor: "#565EEF",
        userPanelBackground: "#FFF",
        userPanelBorderColor: "rgba(148, 166, 190, 0.4)",
        userPanelShadowColor: "rgba(26, 56, 101, 0.21)",
        formBacground: "#FFF",
        formBorderColor: "#D4DBE5",
        textColor: "#000",
        buttonBorderColor: "#565EEF",
        buttonColor: "#565EEF",
        activeTextColor: "#FFF",
        rangeTrackColor: "#EAEEF6",
        rangeThumbColor: "#94A6BE",
        inputDisabledBackground: "#EAEEF6",
    },
    dark: {
        wrapper: "#151419",
        header: "#20202C",
        logo: "#000",
        userNameColor: "#FFF",
        userPanelBackground: "#202229",
        userPanelBorderColor: "#4E5566",
        userPanelShadowColor: "rgba(148, 166, 190, 0.4)",
        formBacground: "#20202C",
        formBorderColor: "#4E5566",
        textColor: "#FFF",
        buttonBorderColor: "#FFF",
        buttonColor: "#FFF",
        activeTextColor: "#000",
        rangeTrackColor: "#FFF",
        rangeThumbColor: "#565EEF",
        inputDisabledBackground: "#151419",
    },
};